# Generated by Django 4.1.5 on 2023-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_alter_movieratingscore_score_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movieratingscore',
            name='movieratingscore-1upto10',
        ),
        migrations.AddConstraint(
            model_name='movieratingscore',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 10)), name='movieratingscore_1upto10', violation_error_message='A movie rating score must be from 1 up to 10'),
        ),
        migrations.AddConstraint(
            model_name='movieratingscore',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='movie_rating_unique_for_user', violation_error_message='A user cannot have multiple ratings on the same movie'),
        ),
    ]
