# Generated by Django 4.1.5 on 2023-02-11 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imdb', '0003_remove_movieratingscore_movieratingscore-1upto10_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movieratingscore',
            name='movie_rating_unique_for_user',
        ),
        migrations.AddField(
            model_name='movie',
            name='watchers',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='movieratingscore',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='users_movie_rating_unique', violation_error_message='User cannot have multiple ratings on the same movie. Change the existing rating score instead'),
        ),
    ]
