# Generated by Django 4.1.5 on 2023-02-11 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imdb', '0004_remove_movieratingscore_movie_rating_unique_for_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.ManyToManyField(related_name='viewed_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
