# Generated by Django 4.1.5 on 2023-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0005_remove_movie_views_movie_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
