# Generated by Django 4.1.5 on 2023-02-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0007_rename_created_moviecomment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='watchlistentry',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='user_movie_unique_watchlist_entry', violation_error_message='User cannot have multiple watchlist entries on the same movie.'),
        ),
    ]
