# Generated by Django 4.1.5 on 2023-02-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0008_watchlistentry_user_movie_unique_watchlist_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='views',
        ),
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb.movie')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movieview',
            constraint=models.UniqueConstraint(fields=('movie', 'session_key'), name='movie_session_unique_view', violation_error_message='Movie view should be unique for each session and movie'),
        ),
    ]
