# Generated by Django 4.1.5 on 2023-02-21 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imdb', '0009_remove_movie_views_movieview_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movieview',
            name='movie_session_unique_view',
        ),
        migrations.AddField(
            model_name='movieview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movieview',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='imdb.movie'),
        ),
        migrations.AddConstraint(
            model_name='movieview',
            constraint=models.UniqueConstraint(fields=('movie', 'session_key', 'user'), name='movie_session_user_unique_view', violation_error_message='Movie view should be unique for each session/user and movie'),
        ),
    ]
