# Generated by Django 4.1.5 on 2023-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0012_movieview_movie_user_unique_view'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movieview',
            name='movie_session_user_unique_view',
        ),
        migrations.RemoveConstraint(
            model_name='movieview',
            name='movie_user_unique_view',
        ),
        migrations.AddConstraint(
            model_name='movieview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('movie', 'user'), name='movie_user_unique_view', violation_error_message='Movie view should be unique for each user and movie'),
        ),
        migrations.AddConstraint(
            model_name='movieview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('movie', 'session_key'), name='movie_session_user_unique_view', violation_error_message='Movie view should be unique for each anon session and movie'),
        ),
    ]
