# Generated by Django 4.1.5 on 2023-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0013_remove_movieview_movie_session_user_unique_view_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movieview',
            name='movie_session_user_unique_view',
        ),
        migrations.AddConstraint(
            model_name='movieview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('movie', 'session_key'), name='movie_anon_session_unique_view', violation_error_message='Movie view should be unique for each anon session and movie'),
        ),
    ]
