# Generated by Django 5.2.3 on 2025-07-01 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0014_remove_movieview_movie_session_user_unique_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2045)]),
        ),
    ]
